name: 'Continuous Integration'

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-testing:
    name: "Unit testing"
    runs-on: ubuntu-20.04
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.13

      - name: Checkout
        uses: actions/checkout@v2

#      - name: Setup Codacy Analyze Tool
#        run: |
#          curl -L https://github.com/codacy/codacy-analysis-cli/archive/master.tar.gz | \
#          tar xvz && cd codacy-analysis-cli-* && sudo make install \
#          && cd .. && rm -rf master.* codacy-analysis-cli-*

      - name: Formatting
        run: go fmt ./...

      - name: Testing
        run: go test -short ./...

#      - name: Run aligncheck
#        run: |
#          codacy-analysis-cli analyze --provider gh \
#          --username leroy-merlin-br \
#          --project logstash_exporter \
#          --tool aligncheck \
#          --allow-network \
#          --upload \
#          --verbose

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          tool: aligncheck
          run-staticcheck: true
          run-gosec: true
          run-docker-tools: true
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647
